name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Run test script
      run: npm test

    - name: Run Snyk to check for vulnerabilities 
      # Use the action that corresponds to your project type (e.g., /node@master for Node.js) 
      uses: snyk/actions/node@master 
      env: 
        # Use the secret you created in Step 2 for authentication 
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }} 
      with: 
        # 'test' scans for vulnerabilities and fails the build if issues are found 
        command: test 
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
